Name: Build Sphinx documentation
on: [push, pull_request]

jobs:
  sphinx-build:
    name: Build Sphinx documentation
    runs-on: ubuntu-latest
    steps:
    - name: Sphinx Build
      uses: ammaraskar/sphinx-action@0.4
